using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ImportPOC2.Models
{
    internal class ProductRow
    {

        public string Additional_Color { get; set; }
        public string Additional_Info { get; set; }
        public string Additional_Location { get; set; }
        public string Artwork { get; set; }
        public string Base_Price_Criteria_1 { get; set; }
        public string Base_Price_Criteria_2 { get; set; }
        public string Base_Price_Name { get; set; }
        public string Breakout_by_other_attribute { get; set; }
        public string Breakout_by_price { get; set; }
        public string Can_order_only_one { get; set; }
        public string Catalog_Information { get; set; }
        public string Category { get; set; }
        public string Comp_Cert { get; set; }
        public string Confirmed_Thru_Date { get; set; }
        public string Currency { get; set; }
        public string D1 { get; set; }
        public string D10 { get; set; }
        public string D2 { get; set; }
        public string D3 { get; set; }
        public string D4 { get; set; }
        public string D5 { get; set; }
        public string D6 { get; set; }
        public string D7 { get; set; }
        public string D8 { get; set; }
        public string D9 { get; set; }
        public string Description { get; set; }
        public string Disclaimer { get; set; }
        public string Distibutor_Only { get; set; }
        public string Distributor_View_Only { get; set; }
        public string Dont_Make_Active { get; set; }
        public string Imprint_Color { get; set; }
        public string Imprint_Location { get; set; }
        public string Imprint_Method { get; set; }
        public string Imprint_Size { get; set; }
        public string Inventory_Link { get; set; }
        public string Inventory_Quantity { get; set; }
        public string Inventory_Status { get; set; }
        public string Keywords { get; set; }
        public string Less_Than_Min { get; set; }
        public string Linename { get; set; }
        public string Material { get; set; }
        public string Option_Additional_Info { get; set; }
        public string Option_Name { get; set; }
        public string Option_Type { get; set; }
        public string Option_Values { get; set; }
        public string Origin { get; set; }
        public string P1 { get; set; }
        public string P10 { get; set; }
        public string P2 { get; set; }
        public string P3 { get; set; }
        public string P4 { get; set; }
        public string P5 { get; set; }
        public string P6 { get; set; }
        public string P7 { get; set; }
        public string P8 { get; set; }
        public string P9 { get; set; }
        public string Packaging { get; set; }
        public string Personalization { get; set; }
        public string Price_Includes { get; set; }
        public string Price_Type { get; set; }
        public string Prod_Image { get; set; }
        public string Product_Color { get; set; }
        public string Product_Data_Sheet { get; set; }
        public string Product_Inventory_Link { get; set; }
        public string Product_Inventory_Quantity { get; set; }
        public string Product_Inventory_Status { get; set; }
        public string Product_Name { get; set; }
        public string Product_Number { get; set; }
        public string Product_Number_Criteria_1 { get; set; }
        public string Product_Number_Criteria_2 { get; set; }
        public string Product_Number_Other { get; set; }
        public string Product_Number_Price { get; set; }
        public string Product_Sample { get; set; }
        public string Product_SKU { get; set; }
        public string Production_Time { get; set; }
        public string Q1 { get; set; }
        public string Q10 { get; set; }
        public string Q2 { get; set; }
        public string Q3 { get; set; }
        public string Q4 { get; set; }
        public string Q5 { get; set; }
        public string Q6 { get; set; }
        public string Q7 { get; set; }
        public string Q8 { get; set; }
        public string Q9 { get; set; }
        public string QUR_Flag { get; set; }
        public string Req_for_order { get; set; }
        public string Rush_Service { get; set; }
        public string Rush_Time { get; set; }
        public string Safety_Warnings { get; set; }
        public string Same_Day_Service { get; set; }
        public string SEO_FLG { get; set; }
        public string Shape { get; set; }
        public string Ship_Plain_Box { get; set; }
        public string Shipper_Bills_By { get; set; }
        public string Shipping_Dimensions { get; set; }
        public string Shipping_Info { get; set; }
        public string Shipping_Items { get; set; }
        public string Shipping_Weight { get; set; }
        public string Size_Group { get; set; }
        public string Size_Values { get; set; }
        public string SKU { get; set; }
        public string SKU_Based_On { get; set; }
        public string SKU_Criteria_1 { get; set; }
        public string SKU_Criteria_2 { get; set; }
        public string SKU_Criteria_3 { get; set; }
        public string SKU_Criteria_4 { get; set; }
        public string Sold_Unimprinted { get; set; }
        public string Spec_Sample { get; set; }
        public string Summary { get; set; }
        public string Theme { get; set; }
        public string Tradename { get; set; }
        public string U_QUR_Flag { get; set; }
        public string UD1 { get; set; }
        public string UD10 { get; set; }
        public string UD2 { get; set; }
        public string UD3 { get; set; }
        public string UD4 { get; set; }
        public string UD5 { get; set; }
        public string UD6 { get; set; }
        public string UD7 { get; set; }
        public string UD8 { get; set; }
        public string UD9 { get; set; }
        public string UP1 { get; set; }
        public string UP10 { get; set; }
        public string UP2 { get; set; }
        public string UP3 { get; set; }
        public string UP4 { get; set; }
        public string UP5 { get; set; }
        public string UP6 { get; set; }
        public string UP7 { get; set; }
        public string UP8 { get; set; }
        public string UP9 { get; set; }
        public string Upcharge_Criteria_1 { get; set; }
        public string Upcharge_Criteria_2 { get; set; }
        public string Upcharge_Details { get; set; }
        public string Upcharge_Level { get; set; }
        public string Upcharge_Name { get; set; }
        public string Upcharge_Type { get; set; }
        public string UQ1 { get; set; }
        public string UQ10 { get; set; }
        public string UQ2 { get; set; }
        public string UQ3 { get; set; }
        public string UQ4 { get; set; }
        public string UQ5 { get; set; }
        public string UQ6 { get; set; }
        public string UQ7 { get; set; }
        public string UQ8 { get; set; }
        public string UQ9 { get; set; }
        public string XID { get; set; }
    }
}
